### ISSUE TITLE
Add option for 'is ceramic' in streamlit interface

### ISSUE THREAD

**Issue by pedrobcst** [pedrobcst/Xerus#33]
When we are doing powder matching for ceramics it would be a ideal if we could have a check button that would search for 'oxygen' only spaces.

TODO:
- [x] Add a checkbox for ceramic search
- [x] If checkbox is checked, automatically add to ignore_combs all combinations that does not have oxygen
- [x] If an extra specificied ignore_comb is added, merge them if not already in the pre defined one

**Comment by oslopanda** [comment]
Hello,
It is a fantastic work!
Any idea on how we can us this in a jupyter-notebook?
