### ISSUE TITLE
Set HTTP `User-Agent` header for `requests`

### ISSUE THREAD

**Issue by merkys** [pedrobcst/Xerus#37]
It is usually very nice when software presents itself in the HTTP `User-Agent` header. Web browsers almost always present themselves in a verbose but neat way. This way the server-side developers are informed about what software makes requests to their servers, and may occasionally forward common issues to the client developers. Moreover, usage statistics could be drawn at the server-size, which is nice.

Xerus seems to be using Python `requests` package for HTTP requests. By default its `User-Agent` is `python-requests/<version>`. Changing this [seems to be rather simple](https://stackoverflow.com/questions/10606133/sending-user-agent-using-requests-library-in-python). It would be nice to see `Xerus/<version>` at least.

If user privacy is concern, it should not be forgotten that this is F/LOSS, thus anyone concerned with their privacy are free to patch their copy of the client to their liking.

**Comment by pedrobcst** [comment]
Hi merkys,

Thanks for the suggestion. Actually this is a really good request and it something I was not aware of (specially of the server-side developer PoV)
I will setup a default User-Agent header for all requests done by Xerus as suggested in the next PR I make.
