### ISSUE TITLE
CI cannot install gfortran anymore

### ISSUE THREAD

**Issue by pedrobcst** [pedrobcst/Xerus#42]
Recently the CI job is failing at:
```
Unable to locate package libgfortran4
```
This is probably (?) due to newest version of Ubuntu (?, ie at ubuntu-latest). Think how to fix this.

Any ideas @ml-evs ?

**Comment by ml-evs** [comment]
I can make a PR that tests it with `libgfortran5` which is still in the 22.04 repos, but it might be that GSAS is looking for 4 explicitly, so we'd need to download it from somewhere else...

**Comment by ml-evs** [comment]
e.g., https://anaconda.org/conda-forge/libgfortran4 `conda install -c conda-forge libgfortran4`

**Comment by pedrobcst** [comment]
Partially fixed by #44
